name: Publish release on PyPi
 
on:
  release:
    types: [published]
 
jobs:
  build-n-publish:
    name: Build and publish on PyPI
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Build a source tarball and wheel
        run: |
          python -m pip install build
          python -m build

      - name: Publish distribution package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
